<?php

declare(strict_types=1);

use CloudPortal\Application;
use CloudPortal\Controllers\AdvancedVmController;
use CloudPortal\Controllers\AdminController;
use CloudPortal\Controllers\AdminResourceDetailsController;
use CloudPortal\Controllers\AuditController;
use CloudPortal\Controllers\AuthController;
use CloudPortal\Controllers\CatalogController;
use CloudPortal\Controllers\CloudArchitectureController;
use CloudPortal\Controllers\CloudInitController;
use CloudPortal\Controllers\ConsoleController;
use CloudPortal\Controllers\DashboardController;
use CloudPortal\Controllers\DnsSettingsController;
use CloudPortal\Controllers\FirewallController;
use CloudPortal\Controllers\JobController;
use CloudPortal\Controllers\OpenApiController;
use CloudPortal\Controllers\PlacementAdminController;
use CloudPortal\Controllers\ProjectAdminController;
use CloudPortal\Controllers\ProjectCreateController;
use CloudPortal\Controllers\ProxmoxAdminController;
use CloudPortal\Controllers\QuotaAdminController;
use CloudPortal\Controllers\ResourceController;
use CloudPortal\Controllers\SystemController;
use CloudPortal\Controllers\TemplateAdminController;
use CloudPortal\Controllers\VmAssignmentAdminController;
use CloudPortal\Controllers\VmController;
use CloudPortal\Controllers\VmIdentityController;
use CloudPortal\Controllers\WebhookAdminController;
use CloudPortal\Http\Router;

return static function (Router $router, Application $app): void {
    $auth = new AuthController($app);
    $dashboard = new DashboardController($app);
    $cloudArchitecture = new CloudArchitectureController($app);
    $vms = new VmController($app);
    $advancedVms = new AdvancedVmController($app);
    $vmIdentity = new VmIdentityController($app);
    $vmAssignment = new VmAssignmentAdminController($app);
    $jobs = new JobController($app);
    $catalog = new CatalogController($app);
    $resources = new ResourceController($app);
    $admin = new AdminController($app);
    $adminDetails = new AdminResourceDetailsController($app);
    $projectAdmin = new ProjectAdminController($app);
    $projectCreate = new ProjectCreateController($app);
    $proxmoxAdmin = new ProxmoxAdminController($app);
    $quotaAdmin = new QuotaAdminController($app);
    $templateAdmin = new TemplateAdminController($app);
    $system = new SystemController($app);
    $webhooks = new WebhookAdminController($app);
    $placementAdmin = new PlacementAdminController($app);
    $dnsSettings = new DnsSettingsController($app);
    $cloudInit = new CloudInitController($app);
    $audit = new AuditController($app);
    $openApi = new OpenApiController($app);
    $firewall = new FirewallController($app);
    $console = new ConsoleController($app);

    $router->add('GET', '/healthz', [$system, 'health']);
    $router->add('GET', '/readyz', [$system, 'ready']);
    $router->add('GET', '/api/openapi.json', [$openApi, 'spec']);

    $router->add('GET', '/api/v1/me', [$auth, 'me']);
    $router->add('POST', '/api/v1/logout', [$auth, 'logout']);
    $router->add('GET', '/api/v1/dashboard', [$dashboard, 'index']);
    $router->add('GET', '/api/v1/catalog', [$catalog, 'index']);
    $router->add('GET', '/api/v1/cloud/capabilities', [$cloudArchitecture, 'capabilities']);

    $router->add('GET', '/api/v1/ssh-keys', [$cloudInit, 'sshKeys']);
    $router->add('POST', '/api/v1/ssh-keys', [$cloudInit, 'createSshKey']);
    $router->add('DELETE', '/api/v1/ssh-keys/{id}', [$cloudInit, 'deleteSshKey']);
    $router->add('GET', '/api/v1/cloud-init-profiles', [$cloudInit, 'profiles']);
    $router->add('POST', '/api/v1/cloud-init-profiles', [$cloudInit, 'createProfile']);
    $router->add('PATCH', '/api/v1/cloud-init-profiles/{id}', [$cloudInit, 'updateProfile']);
    $router->add('DELETE', '/api/v1/cloud-init-profiles/{id}', [$cloudInit, 'deleteProfile']);
    $router->add('GET', '/api/v1/cloud-init-profiles/{id}/vendor-data', [$cloudInit, 'vendorData']);

    $router->add('GET', '/api/v1/vms', [$vms, 'index']);
    $router->add('POST', '/api/v1/vms', [$vms, 'create']);
    $router->add('GET', '/api/v1/vms/{id}', [$vms, 'show']);
    $router->add('DELETE', '/api/v1/vms/{id}', [$vms, 'delete']);
    $router->add('POST', '/api/v1/vms/{id}/snapshots', [$vms, 'snapshot']);
    $router->add('DELETE', '/api/v1/vms/{id}/snapshots/{snapshotId}', [$vms, 'deleteSnapshot']);
    $router->add('POST', '/api/v1/vms/{id}/snapshots/{snapshotName}/rollback', [$advancedVms, 'rollbackSnapshot']);
    $router->add('POST', '/api/v1/vms/{id}/clone', [$advancedVms, 'cloneVm']);
    $router->add('POST', '/api/v1/vms/{id}/resize', [$vms, 'resize']);
    $router->add('PATCH', '/api/v1/vms/{id}/configuration', [$advancedVms, 'reconfigure']);
    $router->add('PATCH', '/api/v1/vms/{id}/name', [$vmIdentity, 'rename']);
    $router->add('POST', '/api/v1/vms/{id}/disks', [$advancedVms, 'attachDisk']);
    $router->add('DELETE', '/api/v1/vms/{id}/disks/{device}', [$advancedVms, 'detachDisk']);
    $router->add('PUT', '/api/v1/vms/{id}/nics/{device}', [$advancedVms, 'upsertNic']);
    $router->add('DELETE', '/api/v1/vms/{id}/nics/{device}', [$advancedVms, 'deleteNic']);
    $router->add('POST', '/api/v1/vms/{id}/migrate', [$advancedVms, 'migrate']);
    $router->add('GET', '/api/v1/vms/{id}/backups', [$advancedVms, 'backups']);
    $router->add('POST', '/api/v1/vms/{id}/backups', [$advancedVms, 'createBackup']);
    $router->add('POST', '/api/v1/backups/{backupId}/restore', [$advancedVms, 'restoreBackup']);
    $router->add('PATCH', '/api/v1/vms/{id}/assignment', [$vms, 'assign']);
    $router->add('POST', '/api/v1/vms/{id}/console/session', [$console, 'portalSession']);
    $router->add('POST', '/api/v1/vms/{id}/console', [$vms, 'console']);
    $router->add('GET', '/api/v1/vms/{id}/firewall', [$firewall, 'vmState']);
    $router->add('PUT', '/api/v1/vms/{id}/firewall/options', [$firewall, 'vmOptions']);
    $router->add('POST', '/api/v1/vms/{id}/firewall/rules', [$firewall, 'vmRuleCreate']);
    $router->add('PUT', '/api/v1/vms/{id}/firewall/rules/{position}', [$firewall, 'vmRuleUpdate']);
    $router->add('DELETE', '/api/v1/vms/{id}/firewall/rules/{position}', [$firewall, 'vmRuleDelete']);
    $router->add('POST', '/api/v1/vms/{id}/{action}', [$vms, 'power']);
    $router->add('GET', '/api/v1/jobs', [$jobs, 'index']);
    $router->add('GET', '/api/v1/jobs/{id}', [$jobs, 'show']);
    $router->add('GET', '/api/v1/{resource}', [$resources, 'index']);

    $router->add('GET', '/api/v1/admin/audit/search', [$audit, 'search']);
    $router->add('GET', '/api/v1/admin/audit/export', [$audit, 'export']);
    $router->add('GET', '/api/v1/admin/system/health', [$system, 'adminHealth']);
    $router->add('POST', '/api/v1/admin/jobs/{jobId}/retry', [$system, 'retryJob']);
    $router->add('GET', '/api/v1/admin/vms/{id}/assignment-options', [$vmAssignment, 'options']);
    $router->add('GET', '/api/v1/admin/proxmox/{connectionId}/placement', [$system, 'placement']);
    $router->add('GET', '/api/v1/admin/proxmox/{connectionId}/nodes/placement', [$placementAdmin, 'nodes']);
    $router->add('PATCH', '/api/v1/admin/proxmox/{connectionId}/nodes/{node}/placement', [$placementAdmin, 'updateNode']);
    $router->add('GET', '/api/v1/admin/webhooks', [$webhooks, 'index']);
    $router->add('POST', '/api/v1/admin/webhooks', [$webhooks, 'create']);
    $router->add('PATCH', '/api/v1/admin/webhooks/{id}', [$webhooks, 'update']);
    $router->add('DELETE', '/api/v1/admin/webhooks/{id}', [$webhooks, 'delete']);
    $router->add('GET', '/api/v1/admin/webhooks/{id}/deliveries', [$webhooks, 'deliveries']);

    $router->add('GET', '/api/v1/admin/settings', [$dnsSettings, 'listSafe']);
    $router->add('POST', '/api/v1/admin/settings', [$dnsSettings, 'upsertSafe']);
    $router->add('GET', '/api/v1/admin/settings/dns', [$dnsSettings, 'show']);
    $router->add('PUT', '/api/v1/admin/settings/dns', [$dnsSettings, 'update']);
    $router->add('POST', '/api/v1/admin/settings/dns/test', [$dnsSettings, 'test']);
    $router->add('GET', '/api/v1/admin/quota-template-limits', [$quotaAdmin, 'templateLimits']);
    $router->add('POST', '/api/v1/admin/quotas', [$quotaAdmin, 'upsert']);
    $router->add('POST', '/api/v1/admin/quota-template-limits', [$quotaAdmin, 'upsertTemplateLimit']);
    $router->add('DELETE', '/api/v1/admin/quota-template-limits/{id}', [$quotaAdmin, 'deleteTemplateLimit']);
    $router->add('GET', '/api/v1/admin/firewall/connections', [$firewall, 'connections']);
    $router->add('GET', '/api/v1/admin/proxmox/{connectionId}/firewall', [$firewall, 'clusterState']);
    $router->add('POST', '/api/v1/admin/proxmox/{connectionId}/firewall/aliases', [$firewall, 'aliasCreate']);
    $router->add('PUT', '/api/v1/admin/proxmox/{connectionId}/firewall/aliases/{name}', [$firewall, 'aliasUpdate']);
    $router->add('DELETE', '/api/v1/admin/proxmox/{connectionId}/firewall/aliases/{name}', [$firewall, 'aliasDelete']);
    $router->add('POST', '/api/v1/admin/proxmox/{connectionId}/firewall/ipsets', [$firewall, 'ipSetCreate']);
    $router->add('DELETE', '/api/v1/admin/proxmox/{connectionId}/firewall/ipsets/{name}', [$firewall, 'ipSetDelete']);
    $router->add('POST', '/api/v1/admin/proxmox/{connectionId}/firewall/ipsets/{name}/entries', [$firewall, 'ipSetEntryCreate']);
    $router->add('PUT', '/api/v1/admin/proxmox/{connectionId}/firewall/ipsets/{name}/entries', [$firewall, 'ipSetEntryUpdate']);
    $router->add('DELETE', '/api/v1/admin/proxmox/{connectionId}/firewall/ipsets/{name}/entries', [$firewall, 'ipSetEntryDelete']);
    $router->add('POST', '/api/v1/admin/proxmox/{connectionId}/firewall/groups', [$firewall, 'groupCreate']);
    $router->add('DELETE', '/api/v1/admin/proxmox/{connectionId}/firewall/groups/{name}', [$firewall, 'groupDelete']);
    $router->add('POST', '/api/v1/admin/proxmox/{connectionId}/firewall/groups/{name}/rules', [$firewall, 'groupRuleCreate']);
    $router->add('PUT', '/api/v1/admin/proxmox/{connectionId}/firewall/groups/{name}/rules/{position}', [$firewall, 'groupRuleUpdate']);
    $router->add('DELETE', '/api/v1/admin/proxmox/{connectionId}/firewall/groups/{name}/rules/{position}', [$firewall, 'groupRuleDelete']);
    $router->add('GET', '/api/v1/admin/details/{resource}/{id}', [$adminDetails, 'show']);
    $router->add('GET', '/api/v1/admin/{resource}', [$admin, 'index']);
    $router->add('GET', '/api/v1/admin/networks/discovery', [$proxmoxAdmin, 'networkDiscovery']);
    $router->add('GET', '/api/v1/admin/storages/discovery', [$proxmoxAdmin, 'storageDiscovery']);
    $router->add('GET', '/api/v1/admin/templates/discovery', [$proxmoxAdmin, 'templateDiscovery']);
    $router->add('GET', '/api/v1/admin/template-builder/options', [$templateAdmin, 'options']);
    $router->add('POST', '/api/v1/admin/iso-uploads', [$templateAdmin, 'initializeIsoUpload']);
    $router->add('POST', '/api/v1/admin/iso-uploads/{uploadId}/chunks', [$templateAdmin, 'appendIsoChunk']);
    $router->add('POST', '/api/v1/admin/iso-uploads/{uploadId}/complete', [$templateAdmin, 'completeIsoUpload']);
    $router->add('DELETE', '/api/v1/admin/iso-uploads/{uploadId}', [$templateAdmin, 'cancelIsoUpload']);
    $router->add('POST', '/api/v1/admin/template-builder/vms', [$templateAdmin, 'createInstallationVm']);
    $router->add('POST', '/api/v1/admin/template-builder/convert', [$templateAdmin, 'convertVmToTemplate']);
    $router->add('GET', '/api/v1/admin/vms/discovery', [$proxmoxAdmin, 'vmDiscovery']);
    $router->add('GET', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}', [$proxmoxAdmin, 'liveVmDetails']);
    $router->add('POST', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}/status/{action}', [$proxmoxAdmin, 'liveVmPower']);
    $router->add('POST', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}/snapshots', [$proxmoxAdmin, 'liveVmSnapshot']);
    $router->add('DELETE', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}/snapshots/{snapshotName}', [$proxmoxAdmin, 'deleteLiveVmSnapshot']);
    $router->add('POST', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}/console/session', [$console, 'liveSession']);
    $router->add('POST', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}/console', [$proxmoxAdmin, 'liveVmConsole']);
    $router->add('GET', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}/firewall', [$firewall, 'liveState']);
    $router->add('PUT', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}/firewall/options', [$firewall, 'liveOptions']);
    $router->add('POST', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}/firewall/rules', [$firewall, 'liveRuleCreate']);
    $router->add('PUT', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}/firewall/rules/{position}', [$firewall, 'liveRuleUpdate']);
    $router->add('DELETE', '/api/v1/admin/proxmox-vms/{connectionId}/{node}/{vmid}/firewall/rules/{position}', [$firewall, 'liveRuleDelete']);
    $router->add('GET', '/api/v1/admin/projects/{id}', [$projectAdmin, 'show']);
    $router->add('POST', '/api/v1/admin/projects', [$projectCreate, 'create']);
    $router->add('POST', '/api/v1/admin/{resource}', [$admin, 'create']);
    $router->add('PATCH', '/api/v1/admin/{resource}/{id}', [$admin, 'update']);
    $router->add('POST', '/api/v1/admin/proxmox/{id}/sync', [$proxmoxAdmin, 'sync']);
    $router->add('POST', '/api/v1/admin/projects/{id}/members', [$projectAdmin, 'membership']);
    $router->add('POST', '/api/v1/admin/projects/{id}/access', [$projectAdmin, 'access']);
    $router->add('DELETE', '/api/v1/admin/projects/{id}/members/{userId}', [$projectAdmin, 'removeMembership']);
    $router->add('DELETE', '/api/v1/admin/projects/{id}/access/{type}/{resourceId}', [$projectAdmin, 'removeAccess']);
};
